name: Bandit
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '20 12 * * 3'

jobs:
  bandit:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      issues: write
      statuses : read
      pull-requests: write  
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bandit Scan
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with: 
          exit_zero: true # optional, default is DEFAULT
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information.
      - name: Add Comment
        run: gh issue comment 12 --body "Block PR!"
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         #ISSUE: ${{ github.event.issue.html_url }}
         

      

