name: Bandit
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule: 
    - cron: '20 12 * * 3'

jobs:
  bandit:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      issues: write
      statuses : read
      pull-requests: write  
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bandit Scan
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with: 
          exit_zero: true # optional, default is DEFAULT
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information.
          level: HIGH
   #   - name: 'Upload Artifact'
       # uses: actions/upload-artifact@v4
       # with:
       #  name: my-artifact
        # path: ./my_file.txt
         #retention-days: 5
      - name: Add Comment
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         #ISSUE: ${{ github.event.number }}
        run: |
             ls -la
             cat results.sarif
             if grep -E "SEVERITY.HIGH": ^[1-9]\d*$, "results.sarif"; then
             echo "test"
             gh issue comment 12 --body "Block PR!"
             fi
             - gh issue comment 12 --body "Successful"
           
          
        
      
